const movies = [
    {
      name: "Inception",
      releaseDate: "2010-07-16",
      genres: ["Action", "Sci-Fi", "Adventure"],
      language: "English",
    },
    {
      name: "The Shawshank Redemption",
      releaseDate: "1994-09-23",
      genres: ["Drama", "Crime"],
      language: "English",
    },
    {
      name: "The Godfather",
      releaseDate: "1972-03-24",
      genres: ["Crime", "Drama"],
      language: "English",
    },
    {
      name: "The Dark Knight",
      releaseDate: "2008-07-18",
      genres: ["Action", "Crime", "Drama"],
      language: "English",
    },
    {
      name: "Pulp Fiction",
      releaseDate: "1994-10-14",
      genres: ["Crime", "Drama"],
      language: "English",
    },
    {
      name: "Spirited Away",
      releaseDate: "2001-07-20",
      genres: ["Animation", "Adventure", "Family"],
      language: "Japanese",
    },
    {
      name: "Forrest Gump",
      releaseDate: "1994-07-06",
      genres: ["Drama", "Romance"],
      language: "English",
    },
    {
      name: "The Matrix",
      releaseDate: "1999-03-31",
      genres: ["Action", "Sci-Fi"],
      language: "English",
    },
    {
      name: "Titanic",
      releaseDate: "1997-12-19",
      genres: ["Drama", "Romance"],
      language: "English",
    },
    {
      name: "Avatar",
      releaseDate: "2009-12-18",
      genres: ["Action", "Adventure", "Sci-Fi"],
      language: "English",
    },
    {
        name: "The Lord of the Rings: The Fellowship of the Ring",
        releaseDate: "2001-12-19",
        genres: ["Adventure", "Fantasy"],
        language: "English",
      },
      {
        name: "Jurassic Park",
        releaseDate: "1993-06-11",
        genres: ["Action", "Adventure", "Sci-Fi"],
        language: "English",
      },
      {
        name: "The Avengers",
        releaseDate: "2012-05-04",
        genres: ["Action", "Adventure", "Sci-Fi"],
        language: "English",
      },
      {
        name: "Eternal Sunshine of the Spotless Mind",
        releaseDate: "2004-03-19",
        genres: ["Drama", "Romance", "Sci-Fi"],
        language: "English",
      },
      {
        name: "Gladiator",
        releaseDate: "2000-05-05",
        genres: ["Action", "Drama"],
        language: "English",
      },
      {
        name: "Interstellar",
        releaseDate: "2014-11-07",
        genres: ["Adventure", "Drama", "Sci-Fi"],
        language: "English",
      },
      {
        name: "The Revenant",
        releaseDate: "2015-12-25",
        genres: ["Adventure", "Drama", "Western"],
        language: "English",
      },
      {
        name: "The Social Network",
        releaseDate: "2010-10-01",
        genres: ["Biography", "Drama"],
        language: "English",
      },
      {
        name: "Frozen",
        releaseDate: "2013-11-22",
        genres: ["Animation", "Adventure", "Family"],
        language: "English",
      },
      {
        name: "Shawshank Redemption",
        releaseDate: "1994-09-23",
        genres: ["Drama", "Crime"],
        language: "English",
      },
      {
        name: "The Silence of the Lambs",
        releaseDate: "1991-02-14",
        genres: ["Crime", "Drama", "Thriller"],
        language: "English",
      },
      {
        name: "The Grand Budapest Hotel",
        releaseDate: "2014-03-07",
        genres: ["Adventure", "Comedy", "Crime"],
        language: "English",
      },
      {
        name: "The Lion King",
        releaseDate: "1994-06-15",
        genres: ["Animation", "Adventure", "Family"],
        language: "English",
      },
      {
        name: "Mad Max: Fury Road",
        releaseDate: "2015-05-15",
        genres: ["Action", "Adventure", "Sci-Fi"],
        language: "English",
      },
      {
        name: "Black Panther",
        releaseDate: "2018-02-16",
        genres: ["Action", "Adventure", "Sci-Fi"],
        language: "English",
      },
      {
        name: "La La Land",
        releaseDate: "2016-12-25",
        genres: ["Drama", "Music", "Romance"],
        language: "English",
      },
      {
        name: "The Great Gatsby",
        releaseDate: "2013-05-10",
        genres: ["Drama", "Romance"],
        language: "English",
      },
      {
        name: "The Matrix Reloaded",
        releaseDate: "2003-05-15",
        genres: ["Action", "Sci-Fi"],
        language: "English",
      },
      {
        name: "The Matrix Revolutions",
        releaseDate: "2003-11-05",
        genres: ["Action", "Sci-Fi"],
        language: "English",
      },
      {
        name: "The Princess Bride",
        releaseDate: "1987-09-25",
        genres: ["Adventure", "Comedy", "Fantasy"],
        language: "English",
      },
      
  {
    name: "Avengers: Endgame",
    releaseDate: "2019-04-26",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Fight Club",
    releaseDate: "1999-10-15",
    genres: ["Drama"],
    language: "English",
  },
  {
    name: "The Departed",
    releaseDate: "2006-10-06",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
  },
  {
    name: "The Terminator",
    releaseDate: "1984-10-26",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Godfather Part II",
    releaseDate: "1974-12-20",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Spider-Man: No Way Home",
    releaseDate: "2021-12-17",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "English",
  },
  {
    name: "Jurassic Park: The Lost World",
    releaseDate: "1997-05-23",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "A Beautiful Mind",
    releaseDate: "2001-12-21",
    genres: ["Biography", "Drama"],
    language: "English",
  },
  {
    name: "The Shawshank Redemption",
    releaseDate: "1994-09-23",
    genres: ["Drama", "Crime"],
    language: "English",
  },
  {
    name: "Toy Story",
    releaseDate: "1995-11-22",
    genres: ["Animation", "Adventure", "Comedy"],
    language: "English",
  },
  {
    name: "The Dark Knight Rises",
    releaseDate: "2012-07-20",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Lion King",
    releaseDate: "1994-06-15",
    genres: ["Animation", "Adventure", "Family"],
    language: "English",
  },
  {
    name: "The Dark Knight Rises",
    releaseDate: "2012-07-20",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Dark Knight Rises",
    releaseDate: "2012-07-20",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Lion King",
    releaseDate: "1994-06-15",
    genres: ["Animation", "Adventure", "Family"],
    language: "English",
  },
  {
    name: "The Avengers",
    releaseDate: "2012-05-04",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Eternal Sunshine of the Spotless Mind",
    releaseDate: "2004-03-19",
    genres: ["Drama", "Romance", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Inception",
    releaseDate: "2010-07-16",
    genres: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Grand Budapest Hotel",
    releaseDate: "2014-03-07",
    genres: ["Adventure", "Comedy", "Crime"],
    language: "English",
  },
  {
    name: "The Silence of the Lambs",
    releaseDate: "1991-02-14",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
  },
  {
    name: "Jurassic Park",
    releaseDate: "1993-06-11",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Princess Bride",
    releaseDate: "1987-09-25",
    genres: ["Adventure", "Comedy", "Fantasy"],
    language: "English",
  },
  {
    name: "The Departed",
    releaseDate: "2006-10-06",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
  },
  {
    name: "Casablanca",
    releaseDate: "1942-11-26",
    genres: ["Drama", "Romance", "War"],
    language: "English",
  },
  {
    name: "The Sixth Sense",
    releaseDate: "1999-08-06",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "English",
  },
  {
    name: "The Godfather Part III",
    releaseDate: "1990-12-25",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Gone with the Wind",
    releaseDate: "1939-12-15",
    genres: ["Drama", "History", "Romance"],
    language: "English",
  },
  {
    name: "E.T. the Extra-Terrestrial",
    releaseDate: "1982-06-11",
    genres: ["Adventure", "Family", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Die Hard",
    releaseDate: "1988-07-15",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "The Godfather Part II",
    releaseDate: "1974-12-20",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Rocky",
    releaseDate: "1976-11-21",
    genres: ["Drama", "Sport"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "The Great Gatsby",
    releaseDate: "2013-05-10",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Casablanca",
    releaseDate: "1942-11-26",
    genres: ["Drama", "Romance", "War"],
    language: "English",
  },
  {
    name: "The Sixth Sense",
    releaseDate: "1999-08-06",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "English",
  },
  {
    name: "The Godfather Part III",
    releaseDate: "1990-12-25",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Gone with the Wind",
    releaseDate: "1939-12-15",
    genres: ["Drama", "History", "Romance"],
    language: "English",
  },
  {
    name: "E.T. the Extra-Terrestrial",
    releaseDate: "1982-06-11",
    genres: ["Adventure", "Family", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Die Hard",
    releaseDate: "1988-07-15",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "The Godfather Part II",
    releaseDate: "1974-12-20",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Rocky",
    releaseDate: "1976-11-21",
    genres: ["Drama", "Sport"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "The Great Gatsby",
    releaseDate: "2013-05-10",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "The Exorcist",
    releaseDate: "1973-12-26",
    genres: ["Horror"],
    language: "English",
  },
  {
    name: "Seven",
    releaseDate: "1995-09-22",
    genres: ["Crime", "Drama", "Mystery"],
    language: "English",
  },
  {
    name: "The Pianist",
    releaseDate: "2002-09-25",
    genres: ["Biography", "Drama", "Music"],
    language: "English",
  },
  {
    name: "The Godfather Part III",
    releaseDate: "1990-12-25",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "The Prestige",
    releaseDate: "2006-10-20",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Fight Club",
    releaseDate: "1999-10-15",
    genres: ["Drama"],
    language: "English",
  },
  {
    name: "Avatar",
    releaseDate: "2009-12-18",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Matrix Reloaded",
    releaseDate: "2003-05-15",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Matrix Revolutions",
    releaseDate: "2003-11-05",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Shining",
    releaseDate: "1980-05-23",
    genres: ["Drama", "Horror"],
    language: "English",
  },
  {
    name: "Inglourious Basterds",
    releaseDate: "2009-08-21",
    genres: ["Adventure", "Drama", "War"],
    language: "English",
  },
  {
    name: "The Revenant",
    releaseDate: "2015-12-25",
    genres: ["Adventure", "Drama", "Western"],
    language: "English",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "The Dark Knight Rises",
    releaseDate: "2012-07-20",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "Blade Runner",
    releaseDate: "1982-06-25",
    genres: ["Sci-Fi", "Thriller"],
    language: "English",
  },
  {
    name: "The Princess Bride",
    releaseDate: "1987-09-25",
    genres: ["Adventure", "Comedy", "Fantasy"],
    language: "English",
  },
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Apocalypse Now",
    releaseDate: "1979-08-15",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Truman Show",
    releaseDate: "1998-06-05",
    genres: ["Comedy", "Drama", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Jurassic Park: The Lost World",
    releaseDate: "1997-05-23",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "A Beautiful Mind",
    releaseDate: "2001-12-21",
    genres: ["Biography", "Drama"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Lion King",
    releaseDate: "1994-06-15",
    genres: ["Animation", "Adventure", "Family"],
    language: "English",
  },
  {
    name: "The Godfather",
    releaseDate: "1972-03-24",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "Pulp Fiction",
    releaseDate: "1994-10-14",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Spirited Away",
    releaseDate: "2001-07-20",
    genres: ["Animation", "Adventure", "Family"],
    language: "Japanese",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "The Dark Knight Rises",
    releaseDate: "2012-07-20",
    genres: ["Action", "Thriller"],
    language: "English",
  },
  {
    name: "Schindler's List",
    releaseDate: "1993-12-15",
    genres: ["Biography", "Drama", "History"],
    language: "English",
  },
  {
    name: "Forrest Gump",
    releaseDate: "1994-07-06",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "Jaws",
    releaseDate: "1975-06-20",
    genres: ["Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Drama"],
    language: "English",
  },
  {
    name: "The Green Mile",
    releaseDate: "1999-12-10",
    genres: ["Crime", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Sound of Music",
    releaseDate: "1965-03-02",
    genres: ["Biography", "Drama", "Musical"],
    language: "English",
  },
  {
    name: "Saving Private Ryan",
    releaseDate: "1998-07-24",
    genres: ["Drama", "War"],
    language: "English",
  },
  {
    name: "The Matrix",
    releaseDate: "1999-03-31",
    genres: ["Action", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Lord of the Rings: The Return of the King",
    releaseDate: "2003-12-17",
    genres: ["Adventure", "Drama", "Fantasy"],
    language: "English",
  },
  {
    name: "The Lion King",
    releaseDate: "1994-06-15",
    genres: ["Animation", "Adventure", "Family"],
    language: "English",
  },
  {
    name: "The Godfather",
    releaseDate: "1972-03-24",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "Pulp Fiction",
    releaseDate: "1994-10-14",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Spirited Away",
    releaseDate: "2001-07-20",
    genres: ["Animation", "Adventure", "Family"],
    language: "Japanese",
  },
  {
    name: "Inception",
    releaseDate: "2010-07-16",
    genres: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
  },
  {
    name: "The Departed",
    releaseDate: "2006-10-06",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
  },
  {
    name: "American Beauty",
    releaseDate: "1999-09-17",
    genres: ["Drama"],
    language: "English",
  },
  {
    name: "The Silence of the Lambs",
    releaseDate: "1991-02-14",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
  },
  {
    name: "Jurassic Park",
    releaseDate: "1993-06-11",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "Crouching Tiger, Hidden Dragon",
    releaseDate: "2000-12-08",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "Mandarin",
  },
  {
    name: "City of God",
    releaseDate: "2002-02-13",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
  },
  {
    name: "Life is Beautiful",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "War"],
    language: "Italian",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Hero",
    releaseDate: "2002-12-19",
    genres: ["Action", "Adventure", "History"],
    language: "Mandarin",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Oldboy",
    releaseDate: "2003-11-21",
    genres: ["Action", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "Rashomon",
    releaseDate: "1950-08-25",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Japanese",
  },
  {
    name: "Akira",
    releaseDate: "1988-07-16",
    genres: ["Animation", "Action", "Sci-Fi"],
    language: "Japanese",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "Crouching Tiger, Hidden Dragon",
    releaseDate: "2000-12-08",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "Mandarin",
  },
  {
    name: "City of God",
    releaseDate: "2002-02-13",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
  },
  {
    name: "Life is Beautiful",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "War"],
    language: "Italian",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Hero",
    releaseDate: "2002-12-19",
    genres: ["Action", "Adventure", "History"],
    language: "Mandarin",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Oldboy",
    releaseDate: "2003-11-21",
    genres: ["Action", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "Rashomon",
    releaseDate: "1950-08-25",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Japanese",
  },
  {
    name: "Akira",
    releaseDate: "1988-07-16",
    genres: ["Animation", "Action", "Sci-Fi"],
    language: "Japanese",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Y Tu Mamá También",
    releaseDate: "2001-06-08",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "A Separation",
    releaseDate: "2011-03-16",
    genres: ["Drama", "Mystery"],
    language: "Persian",
  },
  {
    name: "Parasite",
    releaseDate: "2019-05-21",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Cinema Paradiso",
    releaseDate: "1988-11-17",
    genres: ["Drama"],
    language: "Italian",
  },
  
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "Crouching Tiger, Hidden Dragon",
    releaseDate: "2000-12-08",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "Mandarin",
  },
  {
    name: "City of God",
    releaseDate: "2002-02-13",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
  },
  {
    name: "Life is Beautiful",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "War"],
    language: "Italian",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Hero",
    releaseDate: "2002-12-19",
    genres: ["Action", "Adventure", "History"],
    language: "Mandarin",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Oldboy",
    releaseDate: "2003-11-21",
    genres: ["Action", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "Rashomon",
    releaseDate: "1950-08-25",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Japanese",
  },
  {
    name: "Akira",
    releaseDate: "1988-07-16",
    genres: ["Animation", "Action", "Sci-Fi"],
    language: "Japanese",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Y Tu Mamá También",
    releaseDate: "2001-06-08",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "A Separation",
    releaseDate: "2011-03-16",
    genres: ["Drama", "Mystery"],
    language: "Persian",
  },
  {
    name: "Parasite",
    releaseDate: "2019-05-21",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
  },
  {
    name: "Cinema Paradiso",
    releaseDate: "1988-11-17",
    genres: ["Drama"],
    language: "Italian",
  },
  {
    name: "Spirited Away",
    releaseDate: "2001-07-20",
    genres: ["Animation", "Adventure", "Family"],
    language: "Japanese",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "The Hunt",
    releaseDate: "2012-01-10",
    genres: ["Drama"],
    language: "Danish",
  },
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "Crouching Tiger, Hidden Dragon",
    releaseDate: "2000-12-08",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "Mandarin",
  },
  {
    name: "City of God",
    releaseDate: "2002-02-13",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
  },
  {
    name: "Life is Beautiful",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "War"],
    language: "Italian",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Hero",
    releaseDate: "2002-12-19",
    genres: ["Action", "Adventure", "History"],
    language: "Mandarin",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Oldboy",
    releaseDate: "2003-11-21",
    genres: ["Action", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "Rashomon",
    releaseDate: "1950-08-25",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Japanese",
  },
  {
    name: "Akira",
    releaseDate: "1988-07-16",
    genres: ["Animation", "Action", "Sci-Fi"],
    language: "Japanese",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Y Tu Mamá También",
    releaseDate: "2001-06-08",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "A Separation",
    releaseDate: "2011-03-16",
    genres: ["Drama", "Mystery"],
    language: "Persian",
  },
  {
    name: "Parasite",
    releaseDate: "2019-05-21",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
  },
  {
    name: "Cinema Paradiso",
    releaseDate: "1988-11-17",
    genres: ["Drama"],
    language: "Italian",
  },
  {
    name: "Spirited Away",
    releaseDate: "2001-07-20",
    genres: ["Animation", "Adventure", "Family"],
    language: "Japanese",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "The Hunt",
    releaseDate: "2012-01-10",
    genres: ["Drama"],
    language: "Danish",
  },
  {
    name: "Rang De Basanti",
    releaseDate: "2006-01-26",
    genres: ["Drama", "History"],
    language: "Hindi",
  },
  {
    name: "Three Idiots",
    releaseDate: "2009-12-25",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "Rang De Basanti",
    releaseDate: "2006-01-26",
    genres: ["Drama", "History"],
    language: "Hindi",
  },
  {
    name: "Three Idiots",
    releaseDate: "2009-12-25",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "Dilwale Dulhania Le Jayenge",
    releaseDate: "1995-10-20",
    genres: ["Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Sholay",
    releaseDate: "1975-08-15",
    genres: ["Action", "Adventure", "Comedy"],
    language: "Hindi",
  },
  {
    name: "Lagaan: Once Upon a Time in India",
    releaseDate: "2001-06-15",
    genres: ["Drama", "Musical", "Sport"],
    language: "Hindi",
  },
  {
    name: "Kabhi Khushi Kabhie Gham",
    releaseDate: "2001-12-14",
    genres: ["Drama", "Musical", "Romance"],
    language: "Hindi",
  },
  {
    name: "Mughal-e-Azam",
    releaseDate: "1960-08-05",
    genres: ["Drama", "Historical", "Romance"],
    language: "Hindi",
  },
  {
    name: "Kuch Kuch Hota Hai",
    releaseDate: "1998-10-16",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Chak De! India",
    releaseDate: "2007-08-10",
    genres: ["Drama", "Family", "Sport"],
    language: "Hindi",
  },
  {
    name: "Mera Naam Joker",
    releaseDate: "1970-12-18",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "My Name Is Khan",
    releaseDate: "2010-02-12",
    genres: ["Drama"],
    language: "Hindi",
  },
  {
    name: "Mother India",
    releaseDate: "1957-02-14",
    genres: ["Drama", "Family"],
    language: "Hindi",
  },
  {
    name: "Swades",
    releaseDate: "2004-12-17",
    genres: ["Drama"],
    language: "Hindi",
  },
  {
    name: "Gol Maal",
    releaseDate: "1979-04-20",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Bajrangi Bhaijaan",
    releaseDate: "2015-07-17",
    genres: ["Action", "Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "Koi Mil Gaya",
    releaseDate: "2003-08-08",
    genres: ["Drama", "Sci-Fi"],
    language: "Hindi",
  },
  {
    name: "Kuch Naa Kaho",
    releaseDate: "2003-08-26",
    genres: ["Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "A Wednesday!",
    releaseDate: "2008-09-05",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Hindi",
  },
  {
    name: "Andhadhun",
    releaseDate: "2018-10-05",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
  },
  {
    name: "Rang De Basanti",
    releaseDate: "2006-01-26",
    genres: ["Drama", "History"],
    language: "Hindi",
  },
  {
    name: "Dilwale Dulhania Le Jayenge",
    releaseDate: "1995-10-20",
    genres: ["Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Sholay",
    releaseDate: "1975-08-15",
    genres: ["Action", "Adventure", "Comedy"],
    language: "Hindi",
  },
  {
    name: "Lagaan: Once Upon a Time in India",
    releaseDate: "2001-06-15",
    genres: ["Drama", "Musical", "Sport"],
    language: "Hindi",
  },
  {
    name: "Kabhi Khushi Kabhie Gham",
    releaseDate: "2001-12-14",
    genres: ["Drama", "Musical", "Romance"],
    language: "Hindi",
  },
  {
    name: "Mughal-e-Azam",
    releaseDate: "1960-08-05",
    genres: ["Drama", "Historical", "Romance"],
    language: "Hindi",
  },
  {
    name: "Kuch Kuch Hota Hai",
    releaseDate: "1998-10-16",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Chak De! India",
    releaseDate: "2007-08-10",
    genres: ["Drama", "Family", "Sport"],
    language: "Hindi",
  },
  {
    name: "Mera Naam Joker",
    releaseDate: "1970-12-18",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "My Name Is Khan",
    releaseDate: "2010-02-12",
    genres: ["Drama"],
    language: "Hindi",
  },
  {
    name: "Mother India",
    releaseDate: "1957-02-14",
    genres: ["Drama", "Family"],
    language: "Hindi",
  },
  {
    name: "Swades",
    releaseDate: "2004-12-17",
    genres: ["Drama"],
    language: "Hindi",
  },
  {
    name: "Gol Maal",
    releaseDate: "1979-04-20",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Bajrangi Bhaijaan",
    releaseDate: "2015-07-17",
    genres: ["Action", "Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "Koi Mil Gaya",
    releaseDate: "2003-08-08",
    genres: ["Drama", "Sci-Fi"],
    language: "Hindi",
  },
  {
    name: "Kuch Naa Kaho",
    releaseDate: "2003-08-26",
    genres: ["Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "A Wednesday!",
    releaseDate: "2008-09-05",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Hindi",
  },
  {
    name: "Andhadhun",
    releaseDate: "2018-10-05",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
  },
  {
    name: "PK",
    releaseDate: "2014-12-19",
    genres: ["Comedy", "Drama", "Sci-Fi"],
    language: "Hindi",
  },
  {
    name: "Bhaag Milkha Bhaag",
    releaseDate: "2013-07-12",
    genres: ["Biography", "Drama", "Sport"],
    language: "Hindi",
  },
  {
    name: "Raajneeti",
    releaseDate: "2010-06-04",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
  },
  {
    name: "Kesari",
    releaseDate: "2019-03-21",
    genres: ["Action", "Drama", "History"],
    language: "Hindi",
  },
  {
    name: "Oldboy",
    releaseDate: "2003-11-21",
    genres: ["Action", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "Parasite",
    releaseDate: "2019-05-21",
    genres: ["Comedy", "Drama", "Thriller"],
    language: "Korean",
  },
  {
    name: "Memories of Murder",
    releaseDate: "2003-05-02",
    genres: ["Crime", "Drama", "Mystery"],
    language: "Korean",
  },
  {
    name: "The Handmaiden",
    releaseDate: "2016-06-01",
    genres: ["Drama", "Romance", "Thriller"],
    language: "Korean",
  },
  {
    name: "Train to Busan",
    releaseDate: "2016-07-20",
    genres: ["Action", "Horror", "Thriller"],
    language: "Korean",
  },
  {
    name: "The Wailing",
    releaseDate: "2016-05-12",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "Korean",
  },
  {
    name: "Burning",
    releaseDate: "2018-05-17",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "Korean",
  },
  {
    name: "I Saw the Devil",
    releaseDate: "2010-08-12",
    genres: ["Crime", "Drama", "Horror"],
    language: "Korean",
  },
  {
    name: "The Man from Nowhere",
    releaseDate: "2010-08-04",
    genres: ["Action", "Crime", "Drama"],
    language: "Korean",
  },
  {
    name: "A Tale of Two Sisters",
    releaseDate: "2003-06-13",
    genres: ["Drama", "Horror", "Mystery"],
    language: "Korean",
  },
  {
    name: "The Host",
    releaseDate: "2006-07-27",
    genres: ["Action", "Drama", "Horror"],
    language: "Korean",
  },
  {
    name: "The Silenced",
    releaseDate: "2015-06-18",
    genres: ["Drama", "Horror", "Mystery"],
    language: "Korean",
  },
  {
    name: "A Taxi Driver",
    releaseDate: "2017-08-02",
    genres: ["Action", "Drama", "History"],
    language: "Korean",
  },
  {
    name: "The Chaser",
    releaseDate: "2008-02-14",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Korean",
  },
  {
    name: "Oasis",
    releaseDate: "2002-08-15",
    genres: ["Drama", "Romance"],
    language: "Korean",
  },
  {
    name: "Spring, Summer, Fall, Winter... and Spring",
    releaseDate: "2003-09-19",
    genres: ["Drama", "Romance"],
    language: "Korean",
  },
  {
    name: "Joint Security Area",
    releaseDate: "2000-09-09",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "Korean",
  },
  {
    name: "Silmido",
    releaseDate: "2003-12-24",
    genres: ["Action", "Drama", "War"],
    language: "Korean",
  },
  {
    name: "The Attorney",
    releaseDate: "2013-12-18",
    genres: ["Biography", "Drama"],
    language: "Korean",
  },
  {
    name: "Miracle in Cell No. 7",
    releaseDate: "2013-01-23",
    genres: ["Comedy", "Drama"],
    language: "Korean",
  },
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "Y Tu Mamá También",
    releaseDate: "2001-06-08",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "The Skin I Live In",
    releaseDate: "2011-09-02",
    genres: ["Drama", "Thriller"],
    language: "Spanish",
  },
  {
    name: "The Others",
    releaseDate: "2001-08-02",
    genres: ["Drama", "Horror", "Mystery"],
    language: "Spanish",
  },
  {
    name: "Talk to Her",
    releaseDate: "2002-03-14",
    genres: ["Drama", "Mystery", "Romance"],
    language: "Spanish",
  },
  {
    name: "The Orphanage",
    releaseDate: "2007-05-20",
    genres: ["Drama", "Horror", "Mystery"],
    language: "Spanish",
  },
  {
    name: "The Devil's Backbone",
    releaseDate: "2001-04-20",
    genres: ["Drama", "Horror"],
    language: "Spanish",
  },
  {
    name: "The Secret in Their Eyes",
    releaseDate: "2009-08-13",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "Biutiful",
    releaseDate: "2010-05-17",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "Julia's Eyes",
    releaseDate: "2010-10-29",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "The Sea Inside",
    releaseDate: "2004-09-03",
    genres: ["Biography", "Drama"],
    language: "Spanish",
  },
  {
    name: "All About My Mother",
    releaseDate: "1999-04-19",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "The Spirit of the Beehive",
    releaseDate: "1973-09-08",
    genres: ["Drama", "Fantasy"],
    language: "Spanish",
  },
  {
    name: "Butterfly",
    releaseDate: "1999-02-12",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "The Nameless",
    releaseDate: "1999-10-29",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "The Others",
    releaseDate: "2001-08-02",
    genres: ["Drama", "Horror", "Mystery"],
    language: "Spanish",
  },
  {
    name: "The Devil's Backbone",
    releaseDate: "2001-04-20",
    genres: ["Drama", "Horror"],
    language: "Spanish",
  },
  {
    name: "The Secret in Their Eyes",
    releaseDate: "2009-08-13",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "Biutiful",
    releaseDate: "2010-05-17",
    genres: ["Drama"],
    language: "Spanish",
  },
  {
    name: "Julia's Eyes",
    releaseDate: "2010-10-29",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Run Lola Run",
    releaseDate: "1998-06-18",
    genres: ["Crime", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Good Bye Lenin!",
    releaseDate: "2003-02-09",
    genres: ["Comedy", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "Downfall",
    releaseDate: "2004-09-16",
    genres: ["Biography", "Drama", "History"],
    language: "German",
  },
  {
    name: "The White Ribbon",
    releaseDate: "2009-06-24",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "German",
  },
  {
    name: "Wings of Desire",
    releaseDate: "1987-05-14",
    genres: ["Drama", "Fantasy", "Romance"],
    language: "German",
  },
  {
    name: "Victoria",
    releaseDate: "2015-06-11",
    genres: ["Crime", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "The Counterfeiters",
    releaseDate: "2007-09-21",
    genres: ["Crime", "Drama", "War"],
    language: "German",
  },
  {
    name: "The Baader Meinhof Complex",
    releaseDate: "2008-09-25",
    genres: ["Action", "Biography", "Crime"],
    language: "German",
  },
  {
    name: "The Edukators",
    releaseDate: "2004-04-19",
    genres: ["Crime", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "The Experiment",
    releaseDate: "2001-03-01",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Goodnight Mommy",
    releaseDate: "2014-08-29",
    genres: ["Drama", "Horror", "Mystery"],
    language: "German",
  },
  {
    name: "The Wave",
    releaseDate: "2008-03-11",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Run Lola Run",
    releaseDate: "1998-06-18",
    genres: ["Crime", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Good Bye Lenin!",
    releaseDate: "2003-02-09",
    genres: ["Comedy", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "Downfall",
    releaseDate: "2004-09-16",
    genres: ["Biography", "Drama", "History"],
    language: "German",
  },
  {
    name: "The White Ribbon",
    releaseDate: "2009-06-24",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "German",
  },
  {
    name: "Wings of Desire",
    releaseDate: "1987-05-14",
    genres: ["Drama", "Fantasy", "Romance"],
    language: "German",
  },
  {
    name: "Victoria",
    releaseDate: "2015-06-11",
    genres: ["Crime", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "La Haine",
    releaseDate: "1995-05-31",
    genres: ["Crime", "Drama"],
    language: "French",
  },
  {
    name: "Blue Is the Warmest Color",
    releaseDate: "2013-10-09",
    genres: ["Drama", "Romance"],
    language: "French",
  },
  {
    name: "The Artist",
    releaseDate: "2011-05-15",
    genres: ["Comedy", "Drama", "Romance"],
    language: "French",
  },
  {
    name: "A Prophet",
    releaseDate: "2009-08-26",
    genres: ["Crime", "Drama"],
    language: "French",
  },
  {
    name: "The Diving Bell and the Butterfly",
    releaseDate: "2007-11-30",
    genres: ["Biography", "Drama"],
    language: "French",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "French",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Breathless",
    releaseDate: "1960-03-16",
    genres: ["Crime", "Drama", "Romance"],
    language: "French",
  },
  {
    name: "A Man and a Woman",
    releaseDate: "1966-05-27",
    genres: ["Drama", "Romance"],
    language: "French",
  },
  {
    name: "La Haine",
    releaseDate: "1995-05-31",
    genres: ["Crime", "Drama"],
    language: "French",
  },
  {
    name: "Blue Is the Warmest Color",
    releaseDate: "2013-10-09",
    genres: ["Drama", "Romance"],
    language: "French",
  },
  {
    name: "The Artist",
    releaseDate: "2011-05-15",
    genres: ["Comedy", "Drama", "Romance"],
    language: "French",
  },
  {
    name: "A Prophet",
    releaseDate: "2009-08-26",
    genres: ["Crime", "Drama"],
    language: "French",
  },
  {
    name: "The Diving Bell and the Butterfly",
    releaseDate: "2007-11-30",
    genres: ["Biography", "Drama"],
    language: "French",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Breathless",
    releaseDate: "1960-03-16",
    genres: ["Crime", "Drama", "Romance"],
    language: "French",
  },
  {
    name: "A Man and a Woman",
    releaseDate: "1966-05-27",
    genres: ["Drama", "Romance"],
    language: "French",
  },
  {
    name: "Dil Chahta Hai",
    releaseDate: "2001-08-10",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
  },
  {
    name: "Devdas",
    releaseDate: "2002-07-12",
    genres: ["Drama", "Musical", "Romance"],
    language: "Hindi",
  },
  {
    name: "Zindagi Na Milegi Dobara",
    releaseDate: "2011-07-15",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "Lunchbox",
    releaseDate: "2013-09-20",
    genres: ["Drama", "Romance"],
    language: "Hindi",
  },
  {
    name: "My Name Is Khan",
    releaseDate: "2010-02-12",
    genres: ["Drama"],
    language: "Hindi",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Good Bye Lenin!",
    releaseDate: "2003-02-09",
    genres: ["Comedy", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Inglourious Basterds",
    releaseDate: "2009-08-21",
    genres: ["Adventure", "Drama", "War"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "Inception",
    releaseDate: "2010-07-16",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Gladiator",
    releaseDate: "2000-05-05",
    genres: ["Action", "Adventure", "Drama"],
    language: "English",
  },
  {
    name: "Pan's Labyrinth",
    releaseDate: "2006-05-27",
    genres: ["Drama", "Fantasy", "War"],
    language: "Spanish",
  },
  {
    name: "The Secret in Their Eyes",
    releaseDate: "2009-08-13",
    genres: ["Drama", "Mystery", "Thriller"],
    language: "Spanish",
  },
  {
    name: "Das Boot",
    releaseDate: "1981-09-17",
    genres: ["Adventure", "Drama", "Thriller"],
    language: "German",
  },
  {
    name: "PK",
    releaseDate: "2014-12-19",
    genres: ["Comedy", "Drama", "Sci-Fi"],
    language: "Hindi",
  },
  {
    name: "Bhaag Milkha Bhaag",
    releaseDate: "2013-07-12",
    genres: ["Biography", "Drama", "Sport"],
    language: "Hindi",
  },
  {
    name: "Raajneeti",
    releaseDate: "2010-06-04",
    genres: ["Crime", "Drama", "Thriller"],
    language: "Hindi",
  },
  {
    name: "Kesari",
    releaseDate: "2019-03-21",
    genres: ["Action", "Drama", "History"],
    language: "Hindi",
  },
  {
    name: "Crouching Tiger, Hidden Dragon",
    releaseDate: "2000-12-08",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "Mandarin",
  },
  {
    name: "Amour",
    releaseDate: "2012-05-20",
    genres: ["Drama", "Romance"],
    language: "French",
  },
  {
    name: "The Pianist",
    releaseDate: "2002-09-25",
    genres: ["Biography", "Drama", "War"],
    language: "English",
  },
  {
    name: "City of God",
    releaseDate: "2002-02-05",
    genres: ["Crime", "Drama"],
    language: "Portuguese",
  },
  {
    name: "The Hunt",
    releaseDate: "2012-05-20",
    genres: ["Drama"],
    language: "Danish",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Goodfellas",
    releaseDate: "1990-09-19",
    genres: ["Biography", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "La La Land",
    releaseDate: "2016-12-09",
    genres: ["Comedy", "Drama", "Music"],
    language: "English",
  },
  {
    name: "Life Is Beautiful",
    releaseDate: "1997-12-20",
    genres: ["Comedy", "Drama", "Romance"],
    language: "Italian",
  },
  {
    name: "Amélie",
    releaseDate: "2001-04-25",
    genres: ["Comedy", "Romance"],
    language: "French",
  },
  {
    name: "The Intouchables",
    releaseDate: "2011-11-02",
    genres: ["Biography", "Comedy", "Drama"],
    language: "French",
  },
  {
    name: "Good Bye Lenin!",
    releaseDate: "2003-02-09",
    genres: ["Comedy", "Drama", "Romance"],
    language: "German",
  },
  {
    name: "The Lives of Others",
    releaseDate: "2006-03-23",
    genres: ["Drama", "Thriller"],
    language: "German",
  },
  {
    name: "Inglourious Basterds",
    releaseDate: "2009-08-21",
    genres: ["Adventure", "Drama", "War"],
    language: "English",
  },
  {
    name: "The Dark Knight",
    releaseDate: "2008-07-18",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "Inception",
    releaseDate: "2010-07-16",
    genres: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
  },
  {
    name: "The Shawshank Redemption",
    releaseDate: "1994-09-23",
    genres: ["Drama", "Crime"],
    language: "English",
  },
  {
    name: "The Godfather",
    releaseDate: "1972-03-24",
    genres: ["Crime", "Drama"],
    language: "English",
  },
  {
    name: "Dune",
    releaseDate: "2021-10-21",
    genres: ["Adventure", "Sci-Fi", "Action"],
    language: "English",
  },
  {
    name: "No Time to Die",
    releaseDate: "2021-09-30",
    genres: ["Action", "Adventure", "Thriller"],
    language: "English",
  },
  {
    name: "Spider-Man: No Way Home",
    releaseDate: "2021-12-17",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "A Quiet Place Part II",
    releaseDate: "2021-05-28",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    language: "English",
  },
  {
    name: "The French Dispatch",
    releaseDate: "2021-10-22",
    genres: ["Comedy", "Drama", "Romance"],
    language: "English",
  },
  {
    name: "The French Dispatch",
    releaseDate: "2021-10-22",
    genres: ["Comedy", "Drama", "Romance"],
    language: "English",
  },
  {
    name: "The Lost City",
    releaseDate: "2022-03-25",
    genres: ["Action", "Adventure", "Comedy"],
    language: "English",
  },
  {
    name: "Avatar 2",
    releaseDate: "2022-12-16",
    genres: ["Action", "Adventure", "Fantasy"],
    language: "English",
  },
  {
    name: "Jurassic World: Dominion",
    releaseDate: "2022-06-10",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "The Batman",
    releaseDate: "2022-03-04",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
  },
  {
    name: "Nope",
    releaseDate: "2022-07-22",
    genres: ["Horror", "Mystery", "Thriller"],
    language: "English",
  },
  {
    name: "Dune: Part Two",
    releaseDate: "2023-10-20",
    genres: ["Adventure", "Sci-Fi", "Action"],
    language: "English",
  },
  {
    name: "The Great Gatsby",
    releaseDate: "2022-12-25",
    genres: ["Drama", "Romance"],
    language: "English",
  },
  {
    name: "The Northman",
    releaseDate: "2022-04-21",
    genres: ["Action", "Adventure", "Drama"],
    language: "English",
  },
  {
    name: "Mad Max: Furiosa",
    releaseDate: "2023-05-12",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  },
  {
    name: "Black Panther: Wakanda Forever",
    releaseDate: "2022-11-10",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
  }
];


   let recommendedMovieNames = [];

    function recommendMovies() {
      const selectedGenres = Array.from(document.getElementById("genres").selectedOptions, (option) => option.value);
      const selectedLanguage = document.getElementById("language").value;
      const selectedReleaseDate = new Date(document.getElementById("releaseDate").value);

      const filteredMovies = movies.filter((movie) => {
        const hasMatchingGenres = selectedGenres.every((genre) => movie.genres.includes(genre));
        const hasMatchingLanguage = selectedLanguage === movie.language;
        const hasMatchingReleaseDate = new Date(movie.releaseDate) >= selectedReleaseDate;
        return hasMatchingGenres && hasMatchingLanguage && hasMatchingReleaseDate;
      });

      const recommendedMoviesList = document.getElementById("recommendedMovies");
      recommendedMoviesList.innerHTML = "";

      filteredMovies.forEach((movie) => {
        if (!recommendedMovieNames.includes(movie.name)) {
          const li = document.createElement("li");
          li.textContent = movie.name;
          recommendedMoviesList.appendChild(li);
          recommendedMovieNames.push(movie.name);
        }
      });
    }
 